version: "3.9"
services:
  fastapi:
    build: .
    container_name: dormitory
    command: bash .sh
    volumes:
      - .:/usr/src/
    ports:
      - "8083:8000"

#    environment:
#      -
    depends_on:
      - db
  db:
    image: bitnami/postgresql
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}