version: '2'

services:
  postgres2:
    image: 'postgres:latest'
    container_name: db2
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=students
  app2:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app2
    ports:
      - "8081:8081"
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db2:5432/students
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

    depends_on:
      - postgres2